version: '3.8'

services:
  node_api:
    container_name: movies_api
    image: movies_api:0.0.1
    build:
      context: .
    ports:
      - "8000:8000"
    environment: 
      - APP_PORT=8000
      - PGDATABASE=api_db
      - PGUSER=oleg
      - PGPASSWORD=superPass
      - PGHOST=node_db
      - JWT_SECRET=superSecret
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=oleg
      - POSTGRES_PASSWORD=superPass
      - POSTGRES_DB=api_db
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}